export const ProductTypeIdMapping = {
 1 :"PL",
 2 :"HL",
 4 :"CC",
 5 :"LAP",
 6 :"CL",
 7 :"FD",
 8 :"TWL",
 9 :"GL",
10 :"EL",
11 :"RD",
12 :"MF",
13 :"BL",
14 :"CDL",
15 :"DEMAT",
16 :"EC",
18 :"DC",
21 :"SA",
22 :"SAL",
23 :"CA",
54 :"HLI",
55 :"TI",
56 :"CI",
57 :"TWI",
58 :"HOI",
59 :"LI",
60 :"TLI",
61 :"CHI",
62 :"WI",
63 :"RI",
64 :"ULIP",
65 :"TD",
66 :"LAS",
67 :"GGLI"
};

export const PageTypeCategoryMapping = {
    TILED_LANDING_PAGE    : {pageType: "PRODUCT", category: "LANDING"},
    CITY                  : {pageType: "PRODUCT", category: "CITY"},
    BANK_PRODUCT          : {pageType: "PRODUCT", category: "BANK"},
    PERMANENT_REDIRECT    : {pageType: "REWRITE"},
    CREDIT_CARD_SPECIFIC  : {pageType: "PRODUCT", category: "CREDIT_CARD"},
    CREDIT_CARD_GROUP     : {pageType: "PRODUCT", category: "CREDIT_CARD_GROUP"},
    REWRITE               : {pageType: "REWRITE"},
    PRODUCT_SPECIFIC_PAGE : {pageType: "PRODUCT", category: "LANDING"},
    SITE_MAP              : {},
    GENERIC               : {pageType: "ARTICLE"},
    COMMODITY             : {pageType: "COMMODITY"},
    INSTITUTION           : {pageType: "CENTER"}
}